name: hotel_booking_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: 0.13.3
  provider: ^6.0.0
  bordered_text: 2.0.0
  get_it: 7.2.0

dev_dependencies:
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
