name: buscatelo
description: Hotel finding. An awesome Flutter challenge.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  random_string: ^1.0.0
  cupertino_icons: ^0.1.2
  flutter_fluid_slider: ^0.0.1
  rflutter_alert: ^1.0.2
  carousel_slider: ^1.3.0
  http: any
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/logo.png"
  image_path_android: "assets/img/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
